-- Baseline schema for Dos Colas — dc-api-v2. Same tables as dc-api's Flyway migrations
-- (V1__init.sql + V2__seed_admin_user.sql). Applied automatically at startup by
-- org.doscolas.db.MigrationRunner — do not run this by hand.

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    phone       VARCHAR(255),
    address     VARCHAR(255),
    enabled     BOOLEAN      NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS pets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(255),
    breed       VARCHAR(255),
    age         INTEGER,
    weight      INTEGER,
    rate        DOUBLE PRECISION,
    owner_id    BIGINT       NOT NULL,
    status      VARCHAR(255),
    notes       VARCHAR(1000),
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_pets_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS pet_sitters (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      BIGINT NOT NULL,
    sitter_id   BIGINT NOT NULL,
    start_date  DATE,
    end_date    DATE,
    status      VARCHAR(255),
    daily_rate  DOUBLE PRECISION,
    notes       VARCHAR(1000),
    assigned_at TIMESTAMP,
    CONSTRAINT fk_pet_sitters_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT fk_pet_sitters_sitter FOREIGN KEY (sitter_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS take_cares (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id       BIGINT NOT NULL,
    sitter_id    BIGINT,
    start_date   DATE   NOT NULL,
    end_date     DATE,
    daily_rate   DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    status       VARCHAR(255),
    notes        VARCHAR(1000),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT fk_take_cares_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT fk_take_cares_sitter FOREIGN KEY (sitter_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS payments (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference       VARCHAR(255)   NOT NULL,
    provider                 VARCHAR(255),
    transbank_token          VARCHAR(255),
    fintoc_payment_intent_id VARCHAR(255),
    buy_order                VARCHAR(255),
    authorization_code       VARCHAR(255),
    card_last_four_digits    VARCHAR(255),
    pet_id                   BIGINT,
    user_id                  BIGINT         NOT NULL,
    take_care_id             BIGINT,
    amount                   NUMERIC(38, 2) NOT NULL,
    platform_fee_amount      NUMERIC(38, 2),
    total_amount             NUMERIC(38, 2),
    currency                 VARCHAR(255),
    status                   VARCHAR(255),
    description              VARCHAR(255),
    created_at               TIMESTAMP,
    paid_at                  TIMESTAMP,
    CONSTRAINT fk_payments_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_payments_take_care FOREIGN KEY (take_care_id) REFERENCES take_cares (id)
);

CREATE TABLE IF NOT EXISTS payouts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id         BIGINT         NOT NULL,
    sitter_id          BIGINT         NOT NULL,
    take_care_id       BIGINT,
    amount             NUMERIC(38, 2) NOT NULL,
    currency           VARCHAR(255),
    status             VARCHAR(255),
    commerce_code      VARCHAR(255),
    authorization_code VARCHAR(255),
    idempotency_key    VARCHAR(255),
    fintoc_transfer_id VARCHAR(255),
    attempts           INTEGER        NOT NULL,
    last_error_message VARCHAR(1000),
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    completed_at       TIMESTAMP,
    CONSTRAINT uk_payouts_payment UNIQUE (payment_id),
    CONSTRAINT fk_payouts_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT fk_payouts_sitter FOREIGN KEY (sitter_id) REFERENCES users (id),
    CONSTRAINT fk_payouts_take_care FOREIGN KEY (take_care_id) REFERENCES take_cares (id)
);

CREATE TABLE IF NOT EXISTS sitter_bank_accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    bank_code      VARCHAR(255) NOT NULL,
    bank_name      VARCHAR(255),
    account_type   VARCHAR(255) NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    rut            VARCHAR(255) NOT NULL,
    holder_name    VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT uk_sitter_bank_accounts_user UNIQUE (user_id),
    CONSTRAINT fk_sitter_bank_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS sitter_commerce_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    commerce_code VARCHAR(255) NOT NULL,
    holder_name   VARCHAR(255),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT uk_sitter_commerce_accounts_user UNIQUE (user_id),
    CONSTRAINT fk_sitter_commerce_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Platform administrator account for the admin dashboard.
-- Credentials: admin@doscolas.cl / admin123 (BCrypt) — CHANGE IN PRODUCTION.
INSERT INTO users (username, email, password, enabled, created_at, updated_at)
SELECT 'admin',
       'admin@doscolas.cl',
       '$2y$10$XDpVuMGau41xtA2nUi38veuA0n26gNh.FPP9c.qeqqAvycrWbfdMW',
       TRUE,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');

INSERT INTO user_roles (user_id, role)
SELECT u.id, 'ADMIN'
FROM users u
WHERE u.username = 'admin'
  AND NOT EXISTS (SELECT 1 FROM user_roles r WHERE r.user_id = u.id AND r.role = 'ADMIN');
