-- Fintoc restored (2026-08-05): Stripe Connect was explored as its replacement but Chile's
-- support for Connect connected accounts is unconfirmed/discouraged, whereas Fintoc is a proven
-- fit for a Chile-only bank-transfer marketplace. Transbank stays removed (V5) — Fintoc is once
-- again the only payment rail.
--
-- This does not simply re-run V4's DROPs in reverse: Fintoc's own API moved on since this was
-- first built. Payment collection used to be a Payment Intent + embedded JS widget
-- (fintoc_payment_intent_id); it's now a Checkout Session, a hosted Fintoc-redirect page
-- (fintoc_checkout_session_id) — no client-side widget/public key needed at all. Payouts
-- (Transfers) still need sitter_bank_accounts/payouts, unchanged in shape from before except
-- commerce_code/authorization_code are dropped (those were the Transbank-settlement columns on
-- payouts, never used by Fintoc's transfer-based payout path).

ALTER TABLE payments ADD COLUMN IF NOT EXISTS fintoc_checkout_session_id VARCHAR(255);

-- The `payments` table is shared with the original dc-api (Hibernate-managed) and carries a stale
-- CHECK constraint from that schema's PaymentStatus enum (PENDING/APPROVED/REJECTED/CANCELLED/
-- REFUNDED/IN_PROCESS) — nothing dc-api-v2's own PaymentStatus (PENDING/COMPLETED/FAILED) ever
-- matches. Undetected until now because no payment provider had successfully completed a payment
-- since dc-api-v2 existed. Dropped rather than replaced: every other status-like column in this
-- schema (take_cares.status, pets.status, payouts.status) relies on the Java enum alone, no DB-level
-- CHECK — consistent with that.
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_status_check;

CREATE TABLE IF NOT EXISTS sitter_bank_accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    bank_code      VARCHAR(255) NOT NULL,
    bank_name      VARCHAR(255),
    account_type   VARCHAR(255) NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    rut            VARCHAR(255) NOT NULL,
    holder_name    VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT uk_sitter_bank_accounts_user UNIQUE (user_id),
    CONSTRAINT fk_sitter_bank_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS payouts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id         BIGINT         NOT NULL,
    sitter_id          BIGINT         NOT NULL,
    take_care_id       BIGINT,
    amount             NUMERIC(38, 2) NOT NULL,
    currency           VARCHAR(255),
    status             VARCHAR(255),
    idempotency_key    VARCHAR(255),
    fintoc_transfer_id VARCHAR(255),
    attempts           INTEGER        NOT NULL,
    last_error_message VARCHAR(1000),
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    completed_at       TIMESTAMP,
    CONSTRAINT uk_payouts_payment UNIQUE (payment_id),
    CONSTRAINT fk_payouts_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT fk_payouts_sitter FOREIGN KEY (sitter_id) REFERENCES users (id),
    CONSTRAINT fk_payouts_take_care FOREIGN KEY (take_care_id) REFERENCES take_cares (id)
);
